name: 'arab_acmg_dbt'
version: '1.0.0'
config-version: 2

profile: 'arab_acmg_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  arab_acmg_dbt:
    +schema: arab_acmg_harmonized
    brca_gene_windows_seed:
      +column_types:
        gene_symbol: string
        ensembl_gene_id: string
        chrom38: string
        chrom_nochr: string
        start_pos38: int64
        end_pos38: int64
        coordinate_source: string
        coordinate_source_url: string
        accessed_at: date
        coordinate_note: string

models:
  arab_acmg_dbt:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: view
      +schema: arab_acmg_harmonized
    harmonized:
      +materialized: table
      +schema: arab_acmg_harmonized
